More make restoration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -666,6 +666,7 @@ TIBROWSER
 CPP
 GREP
 EGREP
+HAPPY
 LIBOBJS
 SRC
 DEST
@@ -3621,6 +3622,55 @@ _ACEOF
 fi
 
 
+# Look for Happy, otherwise touch Parser.hs to give current time stamp.
+for ac_prog in happy
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_HAPPY+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$HAPPY"; then
+  ac_cv_prog_HAPPY="$HAPPY" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_HAPPY="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+HAPPY=$ac_cv_prog_HAPPY
+if test -n "$HAPPY"; then
+  { echo "$as_me:$LINENO: result: $HAPPY" >&5
+echo "${ECHO_T}$HAPPY" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$HAPPY" && break
+done
+
+if test "x$HAPPY" = "x"; then
+	{ echo "$as_me:$LINENO: WARNING: Happy not found, you can not change the grammar." >&5
+echo "$as_me: WARNING: Happy not found, you can not change the grammar." >&2;}
+	touch $srcdir/Parser.hs
+fi
+
 # Checks for library functions.
 
 for ac_header in stdlib.h
@@ -3950,6 +4000,7 @@ _ACEOF
 
 fi
 done
+
 
 
 
@@ -4630,13 +4681,14 @@ TIBROWSER!$TIBROWSER$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+HAPPY!$HAPPY$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 SRC!$SRC$ac_delim
 DEST!$DEST$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 55; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 56; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
